### ISSUE TITLE
老铁这个还在更新吗

### ISSUE THREAD

**Issue by lilechao** [techial1042/SIM800C_Arduino#1]

**Comment by techial1042** [comment]
会的 之后用到其他功能 会继续添加

**Comment by lilechao** [comment]
'tmElements_t' has not been declared
   static uint8_t RTCread(tmElements_t &tm);
老铁示例模块报这个错

**Comment by techial1042** [comment]
@lilechao 不好意思，能把问题描述清楚点吗？
我这边是可以正常使用的。
